const actions = {
    AUTH_REGISTER_USER:'AUTH_REGISTER_USER',
    AUTH_REGISTER_USER_SUCCESS:'AUTH_REGISTER_USER_SUCCESS',
    AUTH_REGISTER_USER_FAILED:'AUTH_REGISTER_USER_FAILED',

    AUTH_LOGIN_USER:'AUTH_LOGIN_USER',
    AUTH_LOGIN_USER_SUCCESS:'AUTH_LOGIN_USER_SUCCESS',
    AUTH_LOGIN_USER_FAILED:'AUTH_LOGIN_USER_FAILED',
}

export default actions;